"""Freguesias (civil parishes) of Lisbon — the 24 parishes after the 2012 reform."""

FREGUESIAS = [
    "Ajuda",
    "Alcântara",
    "Alvalade",
    "Areeiro",
    "Arroios",
    "Avenidas Novas",
    "Beato",
    "Belém",
    "Benfica",
    "Campo de Ourique",
    "Campolide",
    "Carnide",
    "Estrela",
    "Lumiar",
    "Marvila",
    "Misericórdia",
    "Olivais",
    "Parque das Nações",
    "Penha de França",
    "Santa Clara",
    "Santa Maria Maior",
    "Santo António",
    "São Domingos de Benfica",
    "São Vicente",
]

# Location maps — parish highlighted within Lisbon. PNGs live in static/freguesias/
# (sourced from observatorio-lisboa.eapn.pt).
MAPS = {
    "Ajuda": "/static/freguesias/ajuda.png",
    "Alcântara": "/static/freguesias/alcantara.png",
    "Alvalade": "/static/freguesias/alvalade.png",
    "Areeiro": "/static/freguesias/areeiro.png",
    "Arroios": "/static/freguesias/arroios.png",
    "Avenidas Novas": "/static/freguesias/avenidasnovas.png",
    "Beato": "/static/freguesias/beato.png",
    "Belém": "/static/freguesias/belem.png",
    "Benfica": "/static/freguesias/benfica.png",
    "Campo de Ourique": "/static/freguesias/campodeourique.png",
    "Campolide": "/static/freguesias/campolide.png",
    "Carnide": "/static/freguesias/carnide.png",
    "Estrela": "/static/freguesias/estrela.png",
    "Lumiar": "/static/freguesias/lumiar.png",
    "Marvila": "/static/freguesias/marvila.png",
    "Misericórdia": "/static/freguesias/misericordia.png",
    "Olivais": "/static/freguesias/olivais.png",
    "Parque das Nações": "/static/freguesias/parquedasnacoes.png",
    "Penha de França": "/static/freguesias/penhadefranca.png",
    "Santa Clara": "/static/freguesias/santaclara.png",
    "Santa Maria Maior": "/static/freguesias/santamariamaior.png",
    "Santo António": "/static/freguesias/santoantonio.png",
    "São Domingos de Benfica": "/static/freguesias/saodomingosdebenfica.png",
    "São Vicente": "/static/freguesias/saovicente.png",
}
