"""Monumentos e marcos de Lisboa."""

MONUMENTS = [
    "Torre de Belém",
    "Mosteiro dos Jerónimos",
    "Castelo de São Jorge",
    "Ponte 25 de Abril",
    "Sé de Lisboa",
    "Aqueduto das Águas Livres",
    "Padrão dos Descobrimentos",
    "Oceanário de Lisboa",
    "Ponte Vasco da Gama",
    "Panteão Nacional",
    "Elevador de Santa Justa",
    "Praça do Comércio",
    "Palácio Nacional da Ajuda",
    "Basílica da Estrela",
    "Igreja de São Roque",
    "Arco da Rua Augusta",
    "Museu Nacional do Azulejo",
    "Igreja do Carmo de Lisboa",
    "Palácio dos Marqueses de Fronteira",
    "MAAT",
    "Centro Cultural de Belém",
    "Museu Nacional dos Coches",
    "Museu de Arte Antiga",
    "Museu Coleção Berardo",
    "Estádio da Luz",
    "Estádio José Alvalade",
    "Estádio do Restelo",
    "Casa dos Bicos",
    "Igreja de Santo António de Lisboa",
    "Convento da Madre de Deus",
    "Palácio Foz",
    "Teatro Nacional D. Maria II",
    "Teatro Nacional de São Carlos",
    "Estação do Rossio",
    "Cais das Colunas",
    "Miradouro de Santa Luzia",
    "Miradouro da Senhora do Monte",
    "Jardim da Estrela",
    "Jardim Botânico de Lisboa",
    "Jardim Zoológico de Lisboa",
    "Estufa Fria",
    "Parque Eduardo VII",
    "Cemitério dos Prazeres",
    "Cemitério do Alto de São João",
    "Mercado da Ribeira",
    "Reservatório da Mãe d'Água",
    "Igreja de São Domingos",
    "Igreja da Graça",
    "Igreja de Santa Engrácia",
    "Convento do Beato",
    "Palácio da Ajuda",
    "Palácio das Necessidades",
    "Pavilhão de Portugal",
    "Mosteiro de São Vicente de Fora",
    "Palácio de Belém",
    "Coliseu dos Recreios",
    "Estação do Cais do Sodré",
    "Convento de São Pedro de Alcântara",
    "Cordoaria Nacional",
]

# Map Portuguese names to English Wikipedia article titles
WIKIPEDIA = {
    "Torre de Belém": "Belém Tower",
    "Mosteiro dos Jerónimos": "Jerónimos Monastery",
    "Castelo de São Jorge": "São Jorge Castle",
    "Ponte 25 de Abril": "25 de Abril Bridge",
    "Sé de Lisboa": "Lisbon Cathedral",
    "Aqueduto das Águas Livres": "Águas Livres Aqueduct",
    "Padrão dos Descobrimentos": "Monument of the Discoveries",
    "Oceanário de Lisboa": "Lisbon Oceanarium",
    "Ponte Vasco da Gama": "Vasco da Gama Bridge",
    "Panteão Nacional": "Church of Santa Engrácia",
    "Elevador de Santa Justa": "Santa Justa Lift",
    "Praça do Comércio": "Praça do Comércio",
    "Palácio Nacional da Ajuda": "Palace of Ajuda",
    "Basílica da Estrela": "Estrela Basilica",
    "Igreja de São Roque": "Igreja de São Roque",
    "Arco da Rua Augusta": "Rua Augusta Arch",
    "Museu Nacional do Azulejo": "National Museum of the Azulejo",
    "Igreja do Carmo de Lisboa": "Carmo Convent",
    "Palácio dos Marqueses de Fronteira": "Palace of the Marquises of Fronteira",
    "MAAT": "Museum of Art, Architecture and Technology",
    "Centro Cultural de Belém": "Belém Cultural Center",
    "Museu Nacional dos Coches": "National Coach Museum",
    "Museu de Arte Antiga": "National Museum of Ancient Art",
    "Museu Coleção Berardo": "Berardo Collection Museum",
    "Estádio da Luz": "Estádio da Luz",
    "Estádio José Alvalade": "Estádio José Alvalade",
    "Estádio do Restelo": "Estádio do Restelo",
    "Casa dos Bicos": "Casa dos Bicos",
    "Igreja de Santo António de Lisboa": "Church of Saint Anthony of Lisbon",
    "Convento da Madre de Deus": "Madre de Deus Convent",
    "Palácio Foz": "Palácio Foz",
    "Teatro Nacional D. Maria II": "D. Maria II National Theatre",
    "Teatro Nacional de São Carlos": "Teatro Nacional de São Carlos",
    "Estação do Rossio": "Rossio railway station",
    "Cais das Colunas": "Cais das Colunas",
    "Miradouro de Santa Luzia": "Igreja de Santa Luzia (Lisbon)",
    "Miradouro da Senhora do Monte": "Miradouro da Senhora do Monte",
    "Jardim da Estrela": "Jardim da Estrela",
    "Jardim Botânico de Lisboa": "Lisbon Botanical Garden",
    "Jardim Zoológico de Lisboa": "Lisbon Zoo",
    "Estufa Fria": "Estufa Fria",
    "Parque Eduardo VII": "Eduardo VII Park",
    "Cemitério dos Prazeres": "Prazeres Cemetery",
    "Cemitério do Alto de São João": "Cemitério do Alto de São João",
    "Mercado da Ribeira": "Time Out Market Lisboa",
    "Reservatório da Mãe d'Água": "Mãe d'Água das Amoreiras Reservoir",
    "Igreja de São Domingos": "Igreja de São Domingos (Lisbon)",
    "Igreja da Graça": "Church of Graça",
    "Igreja de Santa Engrácia": "Church of Santa Engrácia",
    "Convento do Beato": "Convento do Beato",
    "Palácio da Ajuda": "Palace of Ajuda",
    "Palácio das Necessidades": "Necessidades Palace",
    "Pavilhão de Portugal": "Pavilhão de Portugal",
    "Mosteiro de São Vicente de Fora": "Monastery of São Vicente de Fora",
    "Palácio de Belém": "Belém Palace",
    "Coliseu dos Recreios": "Coliseu dos Recreios",
    "Estação do Cais do Sodré": "Cais do Sodré railway station",
    "Convento de São Pedro de Alcântara": "Convent of São Pedro de Alcântara",
    "Cordoaria Nacional": "Cordoaria Nacional",
}

# Freguesia (parish) where each monument is located
FREGUESIAS = {
    "Torre de Belém": "Belém",
    "Mosteiro dos Jerónimos": "Belém",
    "Castelo de São Jorge": "Santa Maria Maior",
    "Ponte 25 de Abril": "Alcântara",
    "Sé de Lisboa": "Santa Maria Maior",
    "Aqueduto das Águas Livres": "Campolide",
    "Padrão dos Descobrimentos": "Belém",
    "Oceanário de Lisboa": "Parque das Nações",
    "Ponte Vasco da Gama": "Parque das Nações",
    "Panteão Nacional": "São Vicente",
    "Elevador de Santa Justa": "Santa Maria Maior",
    "Praça do Comércio": "Santa Maria Maior",
    "Palácio Nacional da Ajuda": "Ajuda",
    "Basílica da Estrela": "Estrela",
    "Igreja de São Roque": "Misericórdia",
    "Arco da Rua Augusta": "Santa Maria Maior",
    "Museu Nacional do Azulejo": "Beato",
    "Igreja do Carmo de Lisboa": "Santa Maria Maior",
    "Palácio dos Marqueses de Fronteira": "São Domingos de Benfica",
    "MAAT": "Belém",
    "Centro Cultural de Belém": "Belém",
    "Museu Nacional dos Coches": "Belém",
    "Museu de Arte Antiga": "Estrela",
    "Museu Coleção Berardo": "Belém",
    "Estádio da Luz": "São Domingos de Benfica",
    "Estádio José Alvalade": "Lumiar",
    "Estádio do Restelo": "Belém",
    "Casa dos Bicos": "Santa Maria Maior",
    "Igreja de Santo António de Lisboa": "Santa Maria Maior",
    "Convento da Madre de Deus": "Beato",
    "Palácio Foz": "Santo António",
    "Teatro Nacional D. Maria II": "Santa Maria Maior",
    "Teatro Nacional de São Carlos": "Misericórdia",
    "Estação do Rossio": "Santa Maria Maior",
    "Cais das Colunas": "Santa Maria Maior",
    "Miradouro de Santa Luzia": "Santa Maria Maior",
    "Miradouro da Senhora do Monte": "São Vicente",
    "Jardim da Estrela": "Estrela",
    "Jardim Botânico de Lisboa": "Santo António",
    "Jardim Zoológico de Lisboa": "São Domingos de Benfica",
    "Estufa Fria": "Avenidas Novas",
    "Parque Eduardo VII": "Avenidas Novas",
    "Cemitério dos Prazeres": "Estrela",
    "Cemitério do Alto de São João": "Penha de França",
    "Mercado da Ribeira": "Misericórdia",
    "Reservatório da Mãe d'Água": "Santo António",
    "Igreja de São Domingos": "Santa Maria Maior",
    "Igreja da Graça": "São Vicente",
    "Igreja de Santa Engrácia": "São Vicente",
    "Convento do Beato": "Beato",
    "Palácio da Ajuda": "Ajuda",
    "Palácio das Necessidades": "Estrela",
    "Pavilhão de Portugal": "Parque das Nações",
    "Mosteiro de São Vicente de Fora": "São Vicente",
    "Palácio de Belém": "Belém",
    "Coliseu dos Recreios": "Santo António",
    "Estação do Cais do Sodré": "Misericórdia",
    "Convento de São Pedro de Alcântara": "Misericórdia",
    "Cordoaria Nacional": "Belém",
}
